{% set name = "Orange3-Textable" %}
{% set version = "3.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3c3fca80fdc634fbb650cf01d55a1fe1a9fb448d0630d2c873ca807e18f2cf9c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - appdirs
    - chardet
    - lttl >=2.1.0
    - orange3
    - pycountry
    - python >={{ python_min }}
    - setuptools
    - treetaggerwrapper

test:
  imports:
    - _textable
    - _textable.widgets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://textable.io
  summary: Textable add-on for Orange 3 data mining software package.
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://github.com/axanthos/orange3-textable
  doc_url: https://orange3-textable.readthedocs.io/
  description: |
    Textable is an open source add-on bringing advanced text-analytical functionalities to the Orange Canvas data mining software package (itself open source).

extra:
  recipe-maintainers:
    - HeavyTony2
