{% set name = "Orange3-Textable" %}
{% set version = "3.1.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Orange3-Textable-{{ version }}.tar.gz
  sha256: 87b070592d6f36bc31f6ae25812ce1b41d058b2a7bd974ef7c66d71319f8bf3a

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - appdirs
    - chardet
    - future
    - lttl >=2.0.12
    - orange3 >=3.14.0
    - pycountry
    - python >={{ python_min }}
    - setuptools
    - treetaggerwrapper

test:
  imports:
    - _textable
    - _textable.widgets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://textable.io
  summary: Textable add-on for Orange 3 data mining software package.
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://github.com/axanthos/orange3-textable
  doc_url: https://orange3-textable.readthedocs.io/
  description: Textable is an open source add-on bringing advanced text-analytical functionalities to the Orange Canvas data mining software package (itself open source).

extra:
  recipe-maintainers:
    - HeavyTony2
