{% set name = "Orange3-Textable" %}
{% set version = "3.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') | lower }}-{{ version }}.tar.gz
  sha256: 021df5f1c9bf7e08c6536f969d8e832946cc88ab5494848551c0660720a0a475

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools =60.9.3  #the package is getting old and is having issues with newer pip and setuptools version
    - pip =22.0.3 #last known version working
  run:
    - appdirs
    - chardet
    - lttl >=2.1.0
    - orange3
    - pycountry
    - python >={{ python_min }}
    - setuptools
    - treetaggerwrapper

test:
  imports:
    - _textable
    - _textable.widgets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://textable.io
  summary: Textable add-on for Orange 3 data mining software package.
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://github.com/axanthos/orange3-textable
  doc_url: https://orange3-textable.readthedocs.io/
  description: |
    Textable is an open source add-on bringing advanced text-analytical functionalities to the Orange Canvas data mining software package (itself open source).

extra:
  recipe-maintainers:
    - HeavyTony2
